# Generated by Django 5.2.1 on 2025-05-23 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horariodisponivel',
            name='barbeiro',
            field=models.ForeignKey(limit_choices_to={'is_barbeiro': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.horariodisponivel'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.servico'),
        ),
        migrations.AlterUniqueTogether(
            name='horariodisponivel',
            unique_together={('barbeiro', 'data', 'hora')},
        ),
    ]
