# Generated by Django 5.2.1 on 2025-05-23 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão'), ('manual', 'Manual')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('falhou', 'Falhou')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.agendamento')),
            ],
        ),
    ]
